qualcomm-linux/qcom-deb-images

.github/workflows/debos.yml

Build debos recipe in a fresh container; image is currently discarded.

ci: add workflow to build debos recipe

---

.github/workflows/debos.yml

During some GitHub workflow runs, incus exec commands are randomly
interrupted by:
Error: websocket: close 1006 (abnormal closure): unexpected EOF
It's possible that this is due to an OS update happening during the run,
so pre-emptively do the updates first, which is a good idea for bug
fixes and predicatibility anyway.

ci: debos: Update OS packages first

---

.github/workflows/debos.yml

Docker is supported as a firt-class citizen in GitHub Actions. This change removes a few actions we were having to perform. This change will also make the upcoming move to AWS self-hosted runners easier.

ci: Move from Incus to Docker for image building

---

.github/workflows/debos.yml

Rename /builds to fileserver-builds for clarity and in case we need to expose
others directories.

workflows: Fix typo in fileserver copy

---

README.md
debos-recipes/qualcomm-linux-debian-image.yaml
debos-recipes/qualcomm-linux-debian-rootfs.yaml

Misc cleanups not worth individual PRs.
- **README: Fix filename in UFS flashing example**
- **Remove image filename option**
- **rootfs recipe: Consistent error-handling in shells**
- **recipes: More verbose execution**
- **rootfs: Consistent apt calls**

misc cleanups

---

.github/workflows/debos.yml
README.md
debos-recipes/qualcomm-linux-debian-flash.yaml
debos-recipes/qualcomm-linux-debian-image.yaml
debos-recipes/qualcomm-linux-debian-rootfs.yaml

Recipes:
- add missing descriptions
- rootfs: create a tarball with DTBs
- image: extract partition images
- flash: new recipe to generate flat images
workflows: Generate flashable assets and upload these to fileserver
README: update
Fixes #10

flat images

---

README.md
scripts/disk-image-edit.sh

This is very manual and error-prone, and will be trimmed down as various
components are fixed.

Add alpha instructions to craft a RB1 image

---

.github/workflows/debos.yml
.github/workflows/linux.yml
.github/workflows/u-boot.yml
README.md
debos-recipes/qualcomm-linux-debian-flash.yaml
debos-recipes/qualcomm-linux-debian-image.yaml
debos-recipes/qualcomm-linux-debian-rootfs.yaml
kernel-configs/systemd-boot.config
scripts/build-linux-deb.sh
scripts/build-u-boot-rb1.sh
scripts/disk-image-edit.sh

Progressively implement steps described in the README towards a working flat
image for RB1:
- build an Android boot image of U-Boot for RB1
- build an upstream Linux kernel
- add an option to include more debs in the root fs
- add support for generating flat images for RB1, taking the U-Boot binary as
an input
- use all of this in our CI builds
- copy DTBs to ESP as to allow U-Boot to pickup newer DTs
- pre-install qbootctl as to avoid hitting the ABL failed boot count limit on boot_a

Flat images for RB1

---

debos-recipes/qualcomm-linux-debian-rootfs.yaml

After installation, adbd just comes up automatically on boot and can be
used to open shells or push/pull files.
Fixes: #24

debos: rootfs: Install adbd

---

debos-recipes/qualcomm-linux-debian-rootfs.yaml

Enable WiFi on RB1
- **debos: rootfs: Add userspace needed for ath10k**
- **debos: rootfs: Install firmware from sid**
Fixes #23

Fix RB1 WiFi

---

.github/workflows/debos.yml

Xfce was initially disabled as to limit the size/duration of ours builds, but since we target Xfce by default and we want to use our builds as input for OSS compliance, enable Xfce to have a representative set of packages.

ci: debos: Enable Xfce

---

.github/workflows/debos.yml

These are misc cleanups extracted from the preliminary work to generate SBOMs with Syft – see https://github.com/qualcomm-linux/qcom-deb-images/pull/28
- **workflows: debos: Define BUILD_ID in environment**
- **workflows: debos: Consistent path for downloads**
- **workflows: debos: Consistent indentation**
- **workflows: debos: Drop working-directory default**
- **workflows: debos: Split in smaller steps**
- **workflows: debos: Consistent use of set -ux**
- **workflows: debos: Clarify fileserver's directories**

Cleanup debos recipe

---

scripts/build-linux-deb.sh

Fix a typo testing whether there is a local config fragment. This is
nasty in that it won't fail even under `set -e` as it's under an if
statement.

Linux deb: Fix config fragment usage

---

.github/workflows/linux.yml

Currently, builds are accumulated in the linux-latest dir and multiple
kernels are pulled in the image. Instead, upload each build to separate
directories and maintain a linux-latest symlink pointing at the latest
one.

workflows: linux: Fix accumulation of debs

---

.github/workflows/linux.yml

Fixing typo in directory name introduced in
https://github.com/qualcomm-linux/qcom-deb-images/pull/33.

workflows: linux: Fix directory name on fileserver

---

.github/workflows/shellcheck.yml
scripts/build-linux-deb.sh
scripts/build-u-boot-rb1.sh

This will help catch issues such as https://github.com/qualcomm-linux/qcom-deb-images/pull/34

workflows: Add ShellCheck static analysis job

---

debos-recipes/qualcomm-linux-debian-flash.yaml

From Qualcomm Linux 1.4
Known changes:
- Boot KPI optimizations
- Update memmap holes dynamically as conventional memory
- Minor bug fixes
- Supporting 32-bit OEM ID

debos: flash: v75 of boot binaries for QCM6490

---

.github/workflows/build-daily.yml
.github/workflows/build-on-pr.yml
.github/workflows/build-on-push.yml
.github/workflows/debos.yml

Start moving the build logic into separated files to copy the method of meta-qcom to run PR builds/tests with repo secrets.

Move debos build into separate workflow file

---

.github/workflows/build-daily.yml
.github/workflows/build-on-pr.yml
.github/workflows/build-on-push.yml
.github/workflows/debos.yml
.github/workflows/linux.yml
.github/workflows/publish_artifacts.py
.github/workflows/u-boot.yml

The current artifact upload logic requires the self-hosted runner and the file-server to share the same NFS volume as a means of uploading artifacts. This change decouples that so that we could use any runner and still upload artifacts.
We do this by leveraging the GITHUB_TOKEN included in every CI job (including PRs from forked repositories). This is an ephemeral token only valid during the lifetime of the workflow. By granting it read access to the "security-events" API, our file-serve can assert the token it gets is a valid qualcomm-linux token before allowing an upload to happen.
The upload logic gets a little hard to maintain with inline yaml and shell script, so I've created a Python helper to do the upload. It has a few handy features:
* parallel uploads
* upload progress
* better …

ci: Convert to a newer publishing API

---

.github/workflows/u-boot.yml
README.md
debos-recipes/qualcomm-linux-debian-rootfs.yaml
scripts/build-u-boot-rb1.sh

Enable support for EFI firmware capsule updates via fwupdtool on RB1 U-Boot. fwupd allows to perform over the air EFI firmware capsule updates. U-Boot script is updated to additionally build LVFS cabinet archive which can be deployed on RB1 using:
```
$ sudo fwupdtool install u-boot.cab
```

U-Boot RB1: Add support for EFI firmware capsule updates via fwupdtool

---

.github/workflows/debos.yml
.github/workflows/linux.yml
.github/workflows/u-boot.yml

We have a new set of self-hosted runners that IT is providing. This change updates the labels to choose the correct self-hosted work along with updating the mount points for the persistent NFS volume

ci: Move to new self-hosted runners

---

.github/workflows/linux.yml
README.md
scripts/build-linux-deb.sh

libdw-dev:native was added to Build-Depends-Arch in
657f96cb7c06a2ef85d166f1b055baeb6511c324 and is needed to build linux
debs now.

linux: Add new libdw-dev build-dep

---

.github/workflows/debos.yml
.github/workflows/shellcheck.yml
.github/workflows/static-checks.yml
scripts/syft-license-summary.py

Depends on cleanup work in https://github.com/qualcomm-linux/qcom-deb-images/pull/29
Add a new job to generate SBOMs with Syft

workflows: debos: Generate SBOM of rootfs with syft

---

.github/workflows/build-daily.yml
.github/workflows/build-on-pr.yml
.github/workflows/build-on-push.yml
.github/workflows/debos.yml
.github/workflows/lava-schema-check.yml
.github/workflows/test-pr.yml
.github/workflows/test.yml
ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml
ci/schemacheck.py

Prepare and submit LAVA test jobs using flash.tar.gz archive.

workflows: Submit LAVA test jobs

---

.github/workflows/build-on-push.yml

Test job depends on build, but there was a mistake in the dependency name. This patches fixes the dependency to proper name.

workflows: fix dependency name in build-on-push

---

.github/workflows/linux.yml
.github/workflows/u-boot.yml

Fix weekly and cleanup weekly workflows to use upload-private-artifact action
- **workflows: Update comments for native builds**
- **workflows: Use upload-private-artifact-action**
- **workflows: u-boot: Keep older builds**
- **workflows: linux: Remove transition code**

Fix weekly CI builds for U-Boot and Linux

---

ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml

Update auto_login section in LAVA template to match debian image settings.

ci: Fix Debian user/password in LAVA template

---

.github/workflows/build-overlay-deb.yml

CONFIG_PATH was used during development of this workflow, but we want to
use the workflow_dispatch input.

workflows: build-overlay-deb: Use workflow input

---

.github/workflows/static-checks.yml

Instead of just scripts/*.sh, scan all scripts found in the repository using `file`.
I didn't find a widely accepted mechanism to do this so settled on using `file`. The script is at least not too long to follow, doesn't introduce any external dependency, and is careful to avoid errors from unusual characters in filenames (eg. backslash escapes and carriage returns) to try and be safe against all inputs.
If this pattern works, we could extend it to the other lint checks in this file.

workflows: scan all shell scripts

---

.github/workflows/debos.yml
debos-recipes/qualcomm-linux-debian-flash.yaml

As qcom-ptool renamed partition files to follow platform / machine
names, follow suit and update code and comments to use consistent names
for silicon family, platform and board.

debos: flash: Update to use platform names

---

overlay-debs/mesa-snapshot/mesa-snapshot.yaml

- rusticl: use image_copy_buffer
- zink: enable ioopt by default
- tu: Remove now-redundant tu_trace_render_pass_start()
- rusticl: Fix work group size validation
- freedreno/a6xx: Fix thread calc for dummy kernels
- ir3/isa: ignore bit 54 in alias encoding
- rusticl/formats: support cl_ext_image_unorm_int_2_101010
- rusticl/formats: support CL_UNORM_INT_101010_2
- rusticl/queue: fix wrong_self_convention and needless_borrow clippy warnings
- ci: separate hidden jobs to -inc yml files
- nir: Split lower_vote_eq into int/float versions

mesa-snapshot: bump the commit id to c1ba062a3066

---

.github/workflows/build-overlay-deb.yml

The mesa-snapshot script expects these to run the clean target.
This should ideally be prepared in a clean, well defined environment as
other packages might expect other build-deps for clean. However, the
build itself is run in a clean sbuild.

workflows: build-overlay-deb: Install dh, build-essential

---

debos-recipes/qualcomm-linux-debian-rootfs.yaml

Changes to default groups and packages
- **debos: rootfs: Add debian to audio and render**
- **debos: rootfs: Add Docker**
- **debos: rootfs: Install v4l-utils for media-ctl**

Misc default packages/groups improvements

---

.github/workflows/linux.yml

GitHub is now stricter about this useless and bogus repetition.

workflows: linux: Fix duplicate contents perm

---

.github/workflows/linux.yml

test.yml requires checks write, so provide that.
GitHub is now smarter about not even starting the workflow is permissions aren't met.

workflows: linux: Allow writing test results

---

.github/workflows/debos.yml

This is duplicating concurrency already defined in workflows including
debos.yml, resulting in GitHub warnings such as "Canceling since a
deadlock was detected for concurrency group: 'Build Linux kernel deb and
debos image-refs/heads/main' between a top level workflow and
'debos-mainline-linux'".

workflows: debos: Drop concurrency

---

debos-recipes/qualcomm-linux-debian-rootfs.yaml

Now that Debian #1104039 has been addressed in trixie, this shouldn't be
needed.
Tested by booting the daily image and purging the qrtr-tools package:
WiFi connection still worked.

debos: rootfs: Drop qrtr-tools

---

ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml
ci/lava/qrb2210-rb1/boot.yaml

ci: lava: Run wlan-smoke test on all targets

Add more smoke tests from lava-definitions

---

.github/workflows/debos.yml
debos-recipes/qualcomm-linux-debian-flash.yaml
debos-recipes/qualcomm-linux-debian-rootfs.yaml

Changes to debos recipes to have a more scalable board support approach and add
support for a couple more boards:
- IQ-9 Beta EVK (QCS9100 Ride Rev3 EVK)
- IQ-8 Beta EVK (QCS8300 Ride SX EVK)
Commits:
- **refactor: debos: data-driven flash recipe**
- **fix: debos: Only strip top directories from zips**
- **feat: debos: Add support for IQ-9 Beta EVK**
- **feat: debos: Add support for IQ-8 Beta EVK**

Add support for more boards

---

overlay-debs/mesa-unstable/mesa_25.2.1-1qcom1.debdiff

I've updated the debdiff manually, but I didn't update the patch header, which results in the failure to apply the patch.
Fix the patch header in the debdiff.

mesa-unstable: fix the debdiff

---

debos-recipes/qualcomm-linux-debian-rootfs.yaml

Helps managing Bluetooth devices/settings; fixes: #117.

feat(debos/rootfs): Add blueman

---

.github/workflows/debos.yml
debos-recipes/qualcomm-linux-debian-rootfs.yaml

Add image build information when running debos. Specifically, add build id and variant/flavor to /etc/buildinfo.
- **feat(debos): Add image build information to /etc**
- **feat(ci): Pass our build id to debos builds**
Fixes: #37

Add image build info

---

ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml
ci/lava/qrb2210-rb1/boot.yaml

Currently timing out at 20-25% when downloading, so multiplying the 20mn by 5 and and doubling that to give us a buffer.

fix(ci): Bump download and overall timeouts by 180mn

---

overlay-debs/mesa-unstable/mesa_25.2.2-1qcom1.yaml
overlay-debs/mesa-unstable/mesa_25.2.3-1qcom1.debdiff
overlay-debs/mesa-unstable/mesa_25.2.3-1qcom1.yaml

Update mesa-unstable to the freshly uploaded Mesa 25.2.3-1.

mesa-unstable: update to 25.2.3-1

---

debos-recipes/qualcomm-linux-debian-flash.yaml

Generate contents.xml flash files for Axiom:
- **refactor(debos/flash): Use _ptool as workdir**
- **refactor(debos): Patch partitions.conf instead of .xml**
- **feat(debos)!: Drop now unused disk_image_type**
- **feat(debos): Generate contents.xml**

Generate contents.xml flash files for Axiom

---

debos-recipes/qualcomm-linux-debian-flash.yaml

Adapt to new qcom-ptool platform layout and protect from future changes
- **fix(debos/flash): Adapt to new ptool platforms**
- **fix(debos/flash): Stop tracking latest ptool**

Adapt to new ptool platform layout

---

.github/workflows/debos.yml
debos-recipes/qualcomm-linux-debian-flash.yaml
debos-recipes/qualcomm-linux-debian-rootfs.yaml

feat: debos: Add support for IQ-6 Beta EVK

---

.github/workflows/build-overlay-deb.yml

Use an intermediate env var, sanitized by GitHub, to prevent
exploitation from untrusted user-provided input.
Reported-By: Alessandro Braccio <a.braccio@arduino.cc>
Signed-off-by: Loïc Minier <loic.minier@oss.qualcomm.com>

fix(ci): Sanitize workflow inputs with an env var

---

overlay-debs/mesa-unstable/mesa_25.2.3-1qcom1.yaml
overlay-debs/mesa-unstable/mesa_25.2.4-1~qcom1.debdiff
overlay-debs/mesa-unstable/mesa_25.2.4-1~qcom1.yaml

Update mesa-unstable to the freshly uploaded Mesa 25.2.4-1. Use the version with tilde in it to make sure that it's lower than the version in unstable.

mesa: update to 25.2.4-1
